### ISSUE TITLE
constituents-financials.py does not work

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [datasets/s-and-p-500-companies-financials#5]
Getting the following error when trying to run scripts/constituents-financials.py 
<pre>
 % cd scripts
 % python ./constituents-financials.py 
Traceback (most recent call last):
  File "./constituents-financials.py", line 74, in <module>
    resp = urllib.request.urlopen(query)
  File "/home/rajulocal/miniconda3/envs/py38/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/rajulocal/miniconda3/envs/py38/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/rajulocal/miniconda3/envs/py38/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/rajulocal/miniconda3/envs/py38/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/rajulocal/miniconda3/envs/py38/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/rajulocal/miniconda3/envs/py38/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

 % python --version
Python 3.8.3
</pre>

**Comment by olayway** [comment]
fixed
